#!/bin/sh
# Nova OS rcS — early boot

echo "Nova OS booting..."

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run

mdev -s
hostname nova-os
